### ISSUE TITLE
Package isn't published to NPM

### ISSUE THREAD

**Issue by alex-ketch** [clemsos/metalsmith-scan-images#1]
The package doesn't show up on NPM, making it harder to install.
<img width="717" alt="screen shot 2015-10-13 at 11 15 09 am" src="https://cloud.githubusercontent.com/assets/1646307/10452214/c641dd76-719b-11e5-8a6a-728bbaa6d800.png">

For anyone else trying to install it before it is published, just run the code below instead.
`npm install --save https://github.com/clemsos/metalsmith-scan-images`

**Comment by clemsos** [comment]
oops, sorry. fixed : https://www.npmjs.com/package/metalsmith-scan-images
